AlejandroDiBattista/TUP-25-p3

- TP/61345 - Caro, Tobias/tp1/ejercicio.cs
> Ejercicio tp1

- TP/61679 - Lobo Barrera, Mia de los Angeles/tp1/ejercicio.cs
> TP1 - 61679 Lobo Barrera, Mia de los Angeles

- TP/61247 - Medici Assaf, Abril/tp1/Program.cs
- TP/61247 - Medici Assaf, Abril/tp1/prueba/agenda.csv
Subo los archivos correspondientes al TP1 de Programación TUP. El archivo.csv se encuentra en una carpeta llamada prueba y el archivo correspondiente al código es prueba.cs
> TP 1 Programacion - Abril Medici Assaf

- TP/61624 - Godoy, Alan/tp1/ejercicio.cs
tuve algunos problemas con la función de Leer ,en algunas partes no me reconocía la función y eso me retraso por un momento
> TP1 - 61624 - Godoy, Alan

- TP/61905 - Martinez, Augusto/tp1/ejercicio.cs
> Martinez Augusto 61905

- TP/61535 - Mainardi, Facundo/tp1/ejercicio.cs
Trabajo Practico 1 de programacion 3 comision 5
> FacundoMainardiTp1

- TP/61588 - Mussa, Agustín/tp1/ejercicio.cs
> Update ejercicio.cs  legajo 61588, Mussa Agustin

- TP/61572 - Parrado Navarrete, Alex Daniel/tp1/ejercicio.cs
Tuve complicaciones a la hora de  realizar las funciones y con algunas variables que tuve que pedir ayuda a chatgpt xq no encontraba solucion ante el problema Ademas no comprendi bien el uso de Github Desktop aun
> TP1 - 61572

- TP/61037 - Paz, Rodrigo Federico/tp1/ejercicio.cs
> 61037 - TP1

- TP/61197 - Romano, Alfredo Nicolás/tp1/ejercicio.cs
En el tp estan algunas notas propias de lo que tengo que repasar y/o estudiar de mejor manera, al igual que en el programa hay comentarios sobre algunas ayudas recibidas de la IA y notas al respecto de explicaciones.
> TP1 - 61197 - Alfredo Nicolas Romano

- TP/61140 - Perez, Fernando Alberto/tp1/ejercicio.cs
> tp1 - 61140 Perez, Fernando ALberto.cs

- TP/61290 - Azubel, Tomas/tp1/ejercicio.cs
> 61290 - Azubel Tomas

- TP/61051 - Diaz, Agustin Emanuel/tp1/agenda.csv
- TP/61051 - Diaz, Agustin Emanuel/tp1/ejercicio.cs
> TP1 - 61051 Diaz Agustin Emanuel

- TP/61060 - Fioretti, Elian Enrique/tp1/ejercicio.cs
0.01 - Creación básica de un programa funcional para la carga, modificación y eliminación de datos, así como su visualización y búsqueda interna en el archivo.
> TP1 - 61060

- TP/61794 - Lobo Campero, Hernán Ignacio/tp1/agenda.csv
- TP/61794 - Lobo Campero, Hernán Ignacio/tp1/ejercicio.cs
Trabajo practico I - Agenda de contactos finalizada.
> TP1 - 61794 - Lobo Campero, Hernan

- TP/61688 - García Romano, Lucas/tp1/ejercicio.cs
> TP1 61688 Lucas García

- TP/61122 - Molina Hernando, Nahuel/tp1/ejercicio.cs
> 61122-TP1 Nahuel molina 

- TP/62263 - Orellana, José Augusto/tp1/agenda.csv
- TP/62263 - Orellana, José Augusto/tp1/ejercicio.cs
Profe si no ve muchos cambios realizados es porqué primero los hice pero puse el nombre de rama al revés, y no sabía si se podía cambiar el nombre de la rama, así que hice una nueva y subí los cambios ahí.
> TP1 - 62263 - Orellana José Augusto

- TP/61988 - Villada, Guillermo Nicolás/tp1/agenda.csv
- TP/61988 - Villada, Guillermo Nicolás/tp1/ejercicio.cs
> TP1 - 61988

- TP/61473 - Lagoria García, Tomás Gustavo/tp1/agenda.csv
- TP/61473 - Lagoria García, Tomás Gustavo/tp1/ejercicio.cs
Ingeniero, si es que le es posible estaría bueno que nos avisara si esta en correctas condiciones el trabajo. Desde ya, Muchas gracias.
> 61473-TP1-LagoriaGarciaTomas

- TP/61064 - Racedo, Francisco Nicolas/tp1/ejercicio.cs
> TP1 - 61064 - Racedo, Francisco Nicolás

- TP/61312 - Paz Berrondo, Lucas David/tp1/agenda.csv
- TP/61312 - Paz Berrondo, Lucas David/tp1/ejercicio.cs
Paz Berrondo, Lucas David
Legajo: 61312-tp1
Comision 3
> Implementar funcionalidades de gestión de contactos en la agenda (Comision 3)

- TP/61096 - Suarez Vece, Leandro Andres/TP2/ejercicio.cs
> TP2-61090 Suarez Vece Leandro

- TP/61588 - Mussa, Agustín/TP2/ejercicio.cs
el programa funciona, chiste:
por que la niña ciega murio en el cine?
por que no vio el trailer jajajajajaj
> TP2 - 61588 - Mussa, Agustín

- TP/61052 - Reynoso, Braian Nicolás/TP2/ejercicio.cs
> 61052-tp2-BraianReynoso

- TP/61491 - Acuña, Alejo Gabriel/TP2/ejercicio.cs
> TP2 - 61491 - Acuña, Alejo Gabriel

- TP/61053 - Matas Molina, Agustín/TP2/ejercicio.cs
> tp2-61053-AgustinMatas

- TP/61060 - Fioretti, Elian Enrique/TP2/ejercicio.cs
Conocimiento = 2/10
Estrés = 7/10
> TP2 - 61060

- TP/61914 - Robles, Leandro Gonzalo/TP2/ejercicio.cs
> 61914 - Robles, Leandro Gonzalo

- TP/61535 - Mainardi, Facundo/TP2/ejercicio.cs
> TP2 - 61535 Facundo Mainardi

- TP/61422 - Pedraza, Estaban Daniel/TP2/ejercicio.cs
Corrijo el TP debido a una mal interpretacion del enunciado, Subo cambios.
> TP2 - 61422 - Pedraza Esteban

- TP/61673 - Delgado, Augusto Emanuel/TP2/ejercicio.cs
- TP2-/Program.cs
- TP2-/TP2-.csproj
- TP2-/obj/TP2-.csproj.nuget.dgspec.json
- TP2-/obj/TP2-.csproj.nuget.g.props
- TP2-/obj/TP2-.csproj.nuget.g.targets
- TP2-/obj/project.assets.json
- TP2-/obj/project.nuget.cache
> TP2- 61673

- TP/61667 - Acosta, Maira/TP2/ejercicio.cs
> 61667  - TP2

- TP/61314 - Morales, Ignacion Agustin/TP2/ejercicio.cs
> 61314 - TP2

- TP/61032 - Moya, Mariano/TP2/ejercicio.cs
Implementación de clases para gestión bancaria: Banco, Cliente, Cuenta y Operaciones. Se incluyen funcionalidades de depósitos, retiros, transferencias y pagos, con acumulación de puntos y generación de informes.
> TP2-61032-MoyaMariano

- TP/61680 - Dziewulski, Karen/TP2/ejercicio.cs
> TP2- 61680 Karen Elizabeth Dziewulski

- TP/61450 - Jiménez Paz, Patricio Agustín/TP2/ejercicio.cs
> TP2 - 61450 - Jimenez Paz, Patricio Agustín

- TP/61312 - Paz Berrondo, Lucas David/TP2/ejercicio.cs
Le envió la petición del merge teniendo en cuenta las correcciones a realizar. Estuve leyendo y practicando mas, me di cuenta de los errores que usted me menciono. Espero que este bien ahora
> 61312 tp2 (lucas david paz berrondo)

- TP/61676 - Massey, Maximiliano/TP2/ejercicio.cs
mil disculpas por la tardanza estuve teniendo problemas con el wifi
> TP 61676 - Massey Maximiliano

- TP/61032 - Moya, Mariano/tp3/ejercicio.cs
Implementadas pruebas automatizadas para ListaOrdenada con enteros, cadenas y objetos Contacto. Validaciones de agregar, eliminar, filtrar y ordenamiento.
> TP3-61032-MoyaMariano

- TP/61312 - Paz Berrondo, Lucas David/tp3/ejercicio.cs
> TP3 - 61312 - Paz Berrondo, Lucas David

- TP/61122 - Molina Hernando, Nahuel/tp3/ejercicio.cs
> NAHUEL MOLINA HERNANDO-61122 -TP3

- TP/61125 - Rocha, Luca/tp3/ejercicio.cs
> Rocha Luca TP3

- TP/61060 - Fioretti, Elian Enrique/tp3/ejercicio.cs
Funcional... supongo... espero...
> TP3 - 61060

- TP/61679 - Lobo Barrera, Mia de los Angeles/tp3/ejercicio.cs
> 61679 - Lobo Barrera, Mia de los Angeles

- TP/61572 - Parrado Navarrete, Alex Daniel/TP2/ejercicio.cs
- TP/61572 - Parrado Navarrete, Alex Daniel/tp3/ejercicio.cs
Profesor pude solucionar el problema y para aprovechar decidi mandar el trabajo numero 2 y numero 3 en conjunto
> Ejercicio 2 y 3

- Enunciados/tp3/ejercicio.cs
> TP3-61535-FacundoMainardi

- TP/61680 - Dziewulski, Karen/tp3/ejercicio.cs
> Tp3-61680 Karen Dziewulski

- TP/61221 - Duclós, Marcelo Ezequiel/tp3/ejercicio.cs
> TP3 Correcciones - 61221 - Duclós Marcelo Ezequiel

- TP/61579 - Marti, Gonzalo/TP2/ejercicio.cs
- TP/61579 - Marti, Gonzalo/tp3/ejercicio.cs
Hola profesor, disculpe la demora, estuve teniendo inconvenientes familiares y por eso no pude subir los trabajos a tiempo, desde ya muchas gracias por otra oportunidad.
> 61579 Recuperación del TP2 y TP3

- TP/61141 - Di Clemente, María Antonela/TP2/ejercicio.cs
> TP2-61141-Antonella Di Clemente

- TP/61611 - Coronel, Julieta Antonella/TP2/ejercicio.cs
Recuperacion TP2- 61611 Coronel Julieta
> TP2-recuperacion - 61611

- TP/61318 - Herrera, Dalma Luján/tp1/ejercicio.cs
> tp1_61318_Dalma_Lujan_Herrera

- TP/61141 - Di Clemente, María Antonela/tp3/ejercicio.cs
> TP3_61141_Di Clemente Antonella

- TP/61318 - Herrera, Dalma Luján/TP2/ejercicio.cs
> tp2_61318_Herrera_Dalma_Lujan

- TP/61125 - Rocha, Luca/tp4/Program.cs
> tp 4-61125

- TP/61060 - Fioretti, Elian Enrique/tp5/cliente.cs
- TP/61060 - Fioretti, Elian Enrique/tp5/servidor.cs
> TP5 - 61060

- TP/61732 - Paz, Mikael/tp5/cliente.cs
- TP/61732 - Paz, Mikael/tp5/servidor.cs
Profe hice el commit ayer pero en otro lado me confundi, disculpe la molestia
> servidor.cs

- TP/61096 - Suarez Vece, Leandro Andres/tp5/cliente.cs
- TP/61096 - Suarez Vece, Leandro Andres/tp5/servidor.cs
Tp5-61096 - Suarez  Vece, Leandro Andres
> Tp5-61096 - Suarez  Vece, Leandro Andres

- TP/61200 - Gauna Serrano, Martín Javier/tp5/cliente.csx
- TP/61200 - Gauna Serrano, Martín Javier/tp5/servidor.csx
Buenas noches profesor, disculpe el horario, aqui le mando de nuevo el tp5 que ya lo habia presentado pero en su repositorio no aparece, ya le vuelvo a enviar el tp4 tambien
> 61200-tp5-Gauna Martin

- TP/61197 - Romano, Alfredo Nicolás/tp6/cliente/Pages/Confirmacion.razor
> TP6 - 61197 - Alfredo Nicolas Romano

- TP/61644 - Ortega, Fernando Nicolas/tp6/cliente/Pages/Carrito.razor
- TP/61644 - Ortega, Fernando Nicolas/tp6/cliente/Pages/Home.razor
- TP/61644 - Ortega, Fernando Nicolas/tp6/cliente/Services/ApiService.cs
- TP/61644 - Ortega, Fernando Nicolas/tp6/cliente/Services/CarritoService.cs
- TP/61644 - Ortega, Fernando Nicolas/tp6/cliente/Shared/MainLayout.razor
- TP/61644 - Ortega, Fernando Nicolas/tp6/servidor/Program.cs
- TP/61644 - Ortega, Fernando Nicolas/tp6/servidor/servidor.csproj
Corrección de control de stock, fusiones del carrito(no me da ningún mensaje al confirmas la compra)
> CorreccionFinal-61644-FernandoNicolasOrtega

- TP/62104 - Robledo, Juan Gerardo/tp7/calculadora.html
se realizo con exito la calculadora
> calculadora

- TP/61136 - Sosa, Oscar Ignacio/tp7/calculadora.html
> 61136 sosa oscar tp7

- TP/61794 - Lobo Campero, Hernán Ignacio/tp7/calculadora.html
TP7 Calculadora con React finalizado.
> TP7 - 61794 - Lobo Campero, Hernán Ignacio

- TP/61060 - Fioretti, Elian Enrique/tp7/calculadora.html
Estética parcial y funcionabilidad esperada tal y como en el enunciado.
> 61060 - Fioretti Elian Enrique

- TP/62055 - Ahumada, Aiquén/tp7/calculadora.html
css agregado, con respectivas funciones
> tp7-62055-Ahumada aiquen

- TP/61125 - Rocha, Luca/tp7/calculadora.html
> T.P7   Rocha Luca 61125

- TP/61113 - Oriz Caballero, Juan José/tp7/calculadora.html
> TP 7 61113 - Oriz Caballero, Juan José

- TP/61473 - Lagoria García, Tomás Gustavo/tp7/calculadora.html
calculadora. Use eval, mucho más simple
> TPN7 - 61473 - Lagoria García, Tomás Gustavo 

- TP/61818 - Lopez Tisera, Gaston/tp7/calculadora.html
> 61818-Gaston Lopez Tisera

- TP/61644 - Ortega, Fernando Nicolas/tp7/calculadora.html
> Tp7-61644-FernandoNicolasOrtega

- TP/61905 - Martinez, Augusto/TP2/ejercicio.cs
- TP/61905 - Martinez, Augusto/tp5/cliente.cs
- TP/61905 - Martinez, Augusto/tp5/servidor.cs
- TP/61905 - Martinez, Augusto/tp7/calculadora.html
Augusto martinez 61905 comision 5
> TP2, TP5 y TP7 - 61905 - Martinez, Augusto

- TP/61290 - Azubel, Tomas/tp7/calculadora.html
puede que por accidente haya borrado en algun pull request o commit mi TP, que ya fue aceptado el viernes y el codigo funciona bien en distintos dispositivos, se lo mando de vuelta
> tp7 - 61290 - Borrado por accidente
